### ISSUE TITLE
Third milestone: version 0.7

### ISSUE THREAD

**Issue by Wolfvak** [Wolfvak/BootAnim9#11]
- [x] New configuration format, using plain ASCII text for easier management (fixed with https://github.com/Wolfvak/BootAnim9/commit/7a850f60f34858616bc31a7093cd7ed33d67ab02)
- [x] Add a new chainloader which wastes less space (fixed with https://github.com/Wolfvak/BootAnim9/commit/bbe119dd58a141024f32f9349b666bded1bf9f0e)
- [x] Add screen init (fixes https://github.com/Wolfvak/BootAnim9/issues/10)
- [x] Add double buffering (fixes https://github.com/Wolfvak/BootAnim9/issues/8)

I hope to have these figured out in ~4-6 weeks (late July - early August)

**Comment by urherenow** [comment]
current tree leaves me with a black screen. <4 August>

**Comment by Wolfvak** [comment]
I'm aware of this, currently looking into exactly which commit started breaking things. If anyone's able to test, it'd be highly appreciated since I currently lack the hardware necessary for quick testing (sd card reader :P)

**Comment by urherenow** [comment]
I can't help much 'til November. I'm deploying, like right now.

**Comment by Wolfvak** [comment]
This issues have been fixed in the new BootAnim9 version, coming anytime soon.
